services:
  db:
    container_name: db
    image: "fgftk/mongodb:${MONGODB_VERSION}"
    command: "mongod --bind_ip 0.0.0.0 --port 27017"
    networks:
      open5gs:
        aliases:
          - db.open5gs.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - "0.0.0.0:27017:27017/tcp"

  h-nrf:
    container_name: h-nrf
    image: "fgftk/nrf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/h-nrf.yaml"
    networks:
      open5gs:
        aliases:
          - nrf.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-nrf_config
        target: /etc/open5gs/custom/h-nrf.yaml

  h-ausf:
    container_name: h-ausf
    image: "fgftk/ausf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/h-ausf.yaml"
    networks:
      open5gs:
        aliases:
          - ausf.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-ausf_config
        target: /etc/open5gs/custom/h-ausf.yaml
    depends_on:
      - h-nrf

  h-udm:
    container_name: h-udm
    image: "fgftk/udm-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/h-udm.yaml"
    networks:
      open5gs:
        aliases:
          - udm.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-udm_config
        target: /etc/open5gs/custom/h-udm.yaml
    depends_on:
      - h-nrf

  h-udr:
    container_name: h-udr
    image: "fgftk/udr-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/h-udr.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - udr.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-udr_config
        target: /etc/open5gs/custom/h-udr.yaml
    depends_on:
      - db
      - h-nrf

  h-sepp:
    container_name: h-sepp
    image: "fgftk/sepp-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/h-sepp.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - sepp.5gc.mnc001.mcc001.3gppnetwork.org
    configs:
      - source: h-sepp_config
        target: /etc/open5gs/custom/h-sepp.yaml
    depends_on:
      - h-nrf

  v-nrf:
    container_name: v-nrf
    image: "fgftk/nrf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-nrf.yaml"
    networks:
      open5gs:
        aliases:
          - nrf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-nrf_config
        target: /etc/open5gs/custom/v-nrf.yaml

  v-ausf:
    container_name: v-ausf
    image: "fgftk/ausf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-ausf.yaml"
    networks:
      open5gs:
        aliases:
          - ausf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-ausf_config
        target: /etc/open5gs/custom/v-ausf.yaml
    depends_on:
      - v-nrf

  v-nssf:
    container_name: v-nssf
    image: "fgftk/nssf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-nssf.yaml"
    networks:
      open5gs:
        aliases:
          - nssf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-nssf_config
        target: /etc/open5gs/custom/v-nssf.yaml
    depends_on:
      - v-nrf

  v-bsf:
    container_name: v-bsf
    image: "fgftk/bsf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-bsf.yaml"
    networks:
      open5gs:
        aliases:
          - bsf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-bsf_config
        target: /etc/open5gs/custom/v-bsf.yaml
    depends_on:
      - v-nrf

  v-pcf:
    container_name: v-pcf
    image: "fgftk/pcf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-pcf.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - pcf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-pcf_config
        target: /etc/open5gs/custom/v-pcf.yaml
    depends_on:
      - v-nrf

  v-amf:
    container_name: v-amf
    image: "fgftk/amf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-amf.yaml"
    networks:
      open5gs:
        aliases:
          - amf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-amf_config
        target: /etc/open5gs/custom/v-amf.yaml
    depends_on:
      - v-nrf

  v-smf:
    container_name: v-smf
    image: "fgftk/smf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-smf.yaml"
    networks:
      open5gs:
        aliases:
          - smf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-smf_config
        target: /etc/open5gs/custom/v-smf.yaml
    depends_on:
      - v-nrf
      - v-upf

  v-upf:
    container_name: v-upf
    image: "fgftk/upf-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-upf.yaml"
    networks:
      open5gs:
        aliases:
          - upf.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-upf_config
        target: /etc/open5gs/custom/v-upf.yaml
    privileged: true
    cap_add:
      - NET_ADMIN

  v-sepp:
    container_name: v-sepp
    image: "fgftk/sepp-open5gs:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/v-sepp.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - sepp.5gc.mnc070.mcc999.3gppnetwork.org
    configs:
      - source: v-sepp_config
        target: /etc/open5gs/custom/v-sepp.yaml
    depends_on:
      - v-nrf

  packetrusher:
    container_name: packetrusher
    image: "fgftk/packetrusher:${PACKETRUSHER_VERSION}"
    command: "--config /PacketRusher/config/packetrusher.yaml ue"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - gnb.packetrusher.org
    configs:
      - source: packetrusher_config
        target: /PacketRusher/config/packetrusher.yaml
    privileged: true
    cap_add:
      - ALL
    depends_on:
      - v-amf
      - v-smf
      - v-pcf
      - h-udr
  
  webui:
    container_name: webui
    image: "fgftk/webui-open5gs:${OPEN5GS_VERSION}"
    environment:
      DB_URI: "mongodb://${HOST_IP_ADDRESS}:27017/open5gs"
    ports:
      - "9999:9999"
    depends_on:
      - db

networks:
  open5gs:
    name: open5gs
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ogs
    ipam:
      config:
        - subnet: 10.33.33.0/24

volumes:
  db_data:
    name: open5gs_db_data
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  db_config:
    name: open5gs_db_config
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}

configs:
  h-nrf_config:
    file: ../../configs/roaming/h-nrf.yaml
  h-ausf_config:
    file: ../../configs/roaming/h-ausf.yaml
  h-udm_config:
    file: ../../configs/roaming/h-udm.yaml
  h-udr_config:
    file: ../../configs/roaming/h-udr.yaml
  h-sepp_config:
    file: ../../configs/roaming/h-sepp.yaml
  v-nrf_config:
    file: ../../configs/roaming/v-nrf.yaml
  v-ausf_config:
    file: ../../configs/roaming/v-ausf.yaml
  v-nssf_config:
    file: ../../configs/roaming/v-nssf.yaml
  v-bsf_config:
    file: ../../configs/roaming/v-bsf.yaml
  v-pcf_config:
    file: ../../configs/roaming/v-pcf.yaml
  v-amf_config:
    file: ../../configs/roaming/v-amf.yaml
  v-smf_config:
    file: ../../configs/roaming/v-smf.yaml
  v-upf_config:
    file: ../../configs/roaming/v-upf.yaml
  v-sepp_config:
    file: ../../configs/roaming/v-sepp.yaml
  packetrusher_config:
    file: ../../configs/roaming/packetrusher.yaml